local Constants = {}

Constants.WORK = {
	BASE_GAIN = 1,

	MAX_ACTIONS_PER_SECOND = 5,
	MAX_ACTIONS_PER_SECOND_GAMEPASS = 26,
	NO_LIMIT_GAMEPASS_ID = 0,
	ACTION_BURST = 1,

	CLICK_DEBOUNCE = 0.21,
}

Constants.STUDY = {
	PAGE_BASE_GAIN = 1,
	FACT_CHANCE = 0.1,
	PREVIEW_DURATION = 1.5,
	CORRECT_PROGRESS = 0.2,
	LEARNING_PROGRESS = 0.08,
	FOCUS_BUFF_CHANCE = 0.15,
	FOCUS_BUFF_DURATION = 30,
	FOCUS_BUFF_MULTIPLIER = 2,
	PAGE_DEBOUNCE = 0.35,
}

Constants.EXAM = {
	QUESTIONS = 5,
	PASSING_ANSWERS = 4,
	REVIEW_AFTER_FAILURE = 2,
	QUIZ_SKILL = "kusatori",
	PROMPT_DISTANCE = 14,
}

Constants.FORAGE = {
	CLICKS_PER_EXPONENT_BEHIND = 3,
	PULL_RADIUS = 14,
	CLUMP_SPREAD = 8,
	DIRT_PATCH_SIZE = 4.5,
}

Constants.COOKING = {
	STATION_RADIUS = 18,
	MIN_CLICKS_FRACTION = 0.25,
	CLICKS_PER_RESILIENCE_EXPONENT = 1,
	MAX_CLICKS_PER_SECOND = 1,
	XP_PER_CLICK = 1,
}

Constants.FOOD = {
	DURATION_BASE = 180,
	DURATION_TIER = 300,
	TIER_RARITY_ORDER = 3,
	BONUS_PLAIN = 1,
	BONUS_MEAT = 3,
	AMPLIFIER_ID = "food_amplifier",
	AMPLIFIER_STAT = "foodDuration",
	AMPLIFIER_FACTOR = 1.5,
	AMPLIFIER_DURATION = 300,
	MAX_STACKS_PER_DISH = 99,
}

Constants.MOVEMENT = {
	WALK_SPEED = 16,
	SPRINT_SPEED = 30,
	SPEED_LERP = 0.18,
	JUMP_POWER = 52,
}

Constants.HEALTH = {
	BASE_MAX = 100,
	MAX_PER_RESILIENCE_LOG = 25,
}

Constants.MOB = {
	DEFAULT_RESPAWN_SECONDS = 30,
	SPAWN_CELL_MARGIN = 26,
	SPAWN_PLACEMENT_ATTEMPTS = 32,
	SPAWN_MIN_SPACING = 34,
	SPAWN_MAX_CLEARANCE = 30,
}

Constants.STAMINA = {
	BASE_MAX = 100,
	MAX_PER_GRIT_LOG = 25,

	COST_PER_ACTION = 1.0,
	REGEN_PER_SECOND = 6,
	REGEN_PER_GRIT_LOG = 1.5,

	REST_DURATION = 5,
}

Constants.CURRENCY = {
	YEN = "yen",
	STAMPS = "stamps",

	BASE_YEN_PER_MINUTE = 60,
	WAGE_TICK_INTERVAL = 5,

	WEEDING_YEN_PER_GAIN = 0.25,

	STARTING_YEN = 0,
	STARTING_STAMPS = 0,
}

Constants.SEASON = {
	MULTIPLIER_BASE = 10,
}

Constants.HOME = {
	BASE_COMFORT = 1,
}

Constants.DATA = {
	STORE_NAME = "PlayerProfiles_v1",
	FARM_MAILBOX_STORE_NAME = "FarmCredits_v1",
	KEY_PREFIX = "Player_",
	AUTOSAVE_INTERVAL = 60,
	LOAD_RETRIES = 4,
	RETRY_BACKOFF = 2,
	SCHEMA_VERSION = 6,
}

Constants.REPLICATION = {
	SNAPSHOT_INTERVAL = 0.4,
}

Constants.WORLD = {
	TERRAIN_TOP = -2,
	PLATFORM_TOP = 1,
	PLATFORM_THICKNESS = 4,

	PLAZA_DIAMETER_FRACTION = 0.10,
	PLAZA_MIN_DIAMETER = 170,

	NPC_FOOT_CLEARANCE = 0.2,

	ISLAND_DEPTH = 8,
	SHORE_FALLOFF = 90,

	TERRAIN_TILE = 1024,

	BRIDGE_GAP = 400,
	BRIDGE_WIDTH = 300,

	WALL_HEIGHT = 140,
	WALL_THICKNESS = 12,
	HEDGE_HEIGHT = 6,
	VOID_Y = -60,

	GATE_HEIGHT = 46,
	GATE_PILLAR = 12,
}

Constants.STREAMING = {
	MIN_RADIUS = 256,
	TARGET_RADIUS = 1024,
}

return Constants
