local Components = require(script.Components)
local Glyphs = require(script.Glyphs)
local Motion = require(script.Motion)
local Plant = require(script.Plant)
local Primitives = require(script.Primitives)
local Templates = require(script.Templates)
local Theme = require(script.Theme)
local UI = {}

UI.color = Theme.color
UI.font = Theme.font
UI.radius = Theme.radius
UI.space = Theme.space
UI.text = Theme.text
UI.surface = Theme.surface
UI.elevation = Theme.elevation
UI.opacity = Theme.opacity
UI.Theme = Theme
UI.lighten = Theme.lighten
UI.darken = Theme.darken
UI.readable = Theme.readable
UI.skillColor = Theme.skillColor
UI.motion = Motion
UI.corner = Primitives.corner
UI.stroke = Primitives.stroke
UI.padding = Primitives.padding
UI.gradient = Primitives.gradient
UI.list = Primitives.list
UI.shadow = Primitives.shadow
UI.aspect = Primitives.aspect
UI.grid = Primitives.grid
UI.ring = Primitives.ring
UI.vignette = Primitives.vignette
UI.sheen = Primitives.sheen
UI.innerLine = Primitives.innerLine
UI.focusRing = Primitives.focusRing
UI.divider = Primitives.divider
UI.well = Primitives.well
UI.card = Components.card
UI.label = Components.label
UI.bar = Components.bar
UI.chip = Components.chip
UI.button = Components.button
UI.sign = Components.sign
UI.ticker = Components.ticker
UI.pips = Components.pips
UI.tabs = Components.tabs
UI.modal = Components.modal
UI.iconButton = Components.iconButton
UI.header = Components.header
UI.badge = Components.badge
UI.statTile = Components.statTile
UI.meter = Components.meter
UI.toast = Components.toast
UI.template = Templates.mount
UI.hasTemplate = Templates.exists
UI.Templates = Templates
UI.glyph = Glyphs.render
UI.skillGlyph = Glyphs.forSkill
UI.Glyphs = Glyphs
UI.plant = Plant.draw
UI.Plant = Plant

export type LabelConfig = Components.LabelConfig
export type MountConfig = Templates.MountConfig

return UI
